### ISSUE TITLE
Модуль телепортации

### ISSUE THREAD

**Issue by Fingercomp** [cc-ru/ut-server#3]
Сделать модуль телепортации.

- [x] В конфиг вынести координаты точек.
- [x] Поставить листнер.

**Comment by YuRaNnNzZZ** [comment]
>листнер

СЛУШАТЕЛЬ

**Comment by Fingercomp** [comment]
Не протестили модуль, поэтому открываю.

**Comment by Fingercomp** [comment]
Всё работает, фича готова.
